image: node:16

# Workflow Configuration

pipelines:
  branches:
    master:
      - parallel:
        - step:
            name: Build
            caches:
              - node
            script:
              - npm install
              - echo "VUE_APP_API_GATEWAY_URL=$VUE_APP_API_GATEWAY_URL" > .env
              - npm run build
            artifacts:
              - dist/**
      - step:
          name: Deploy to AWS S3 and invalidate cache
          deployment: Production
          #trigger: manual
          clone:
            enabled: false
          script:
            # sync your files to S3
            - pipe: atlassian/aws-s3-deploy:1.1.0
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                S3_BUCKET: 'managementui'
                LOCAL_PATH: 'dist'
            # triggering a distribution invalidation to refresh the CDN caches
            - pipe: atlassian/aws-cloudfront-invalidate:0.6.0
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                DISTRIBUTION_ID: 'EFDLBIQEIPKNY'
